"""
Phase 17 — Persistent Knowledge Base, Self-Improvement & LLM Independence Test Suite
Tests 1 through 16 + Regressions (Phases 11–16)

TEST 1  — Database initialization, migrations & transaction rollback
TEST 2  — ModelRun registry & execution tracking
TEST 3  — CreativeDecision structured records (zero CoT leakage)
TEST 4  — LearningEvent ingestion & idempotency (duplicate events skipped)
TEST 5  — KnowledgePattern lifecycle (CANDIDATE -> VALIDATED -> ACTIVE -> REJECTED)
TEST 6  — Mathematical Bayesian confidence calculation (no 1-hit wonder false promotion)
TEST 7  — Analytics snapshot to LearningEvent feedback loop
TEST 8  — Experiment framework (hypothesis, variant A/B, winner determination)
TEST 9  — Structured knowledge retrieval for AI planning context
TEST 10 — LLM Replacement Test (LLM_B seamlessly consumes knowledge generated by LLM_A)
TEST 11 — Tenant & project scope isolation (GLOBAL vs ACCOUNT vs PROJECT)
TEST 12 — Security & Zero Secret Leakage Audit
TEST 13 — Portable export & import snapshot integrity
TEST 14 — Concurrent thread safety & ACID transaction isolation
TEST 15 — Failure recovery & corrupted store resilience
TEST 16 — Historical Phase 10 Creative Memory migration
TEST 17 — Phase 15/16 Regression Suite (14/14 tests)
TEST 18 — Phase 14 Regression Suite (41/41 tests)
TEST 19 — Phase 13 Regression Suite (30/30 tests)
TEST 20 — Phase 12 Regression Suite (27/27 tests)
TEST 21 — Phase 11 Regression Suite (23/23 tests)
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import threading
import time
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional

from brain.analytics_models import AnalyticsSnapshot, PerformanceMetrics
from brain.knowledge_database import KnowledgeDatabase
from brain.knowledge_models import (
    CreativeDecision,
    ExperimentRecord,
    ExperimentStatus,
    KnowledgePattern,
    KnowledgeRetrievalContext,
    KnowledgeScope,
    LearningEvent,
    LearningEventType,
    ModelRun,
    PatternStatus,
)
from brain.knowledge_repository import KnowledgeRepository, _calculate_confidence

SEP = "=" * 65


# ─── Tests 1 through 6: Core Storage, Decisions & Confidence ──────────────────

def test_01_db_init_and_rollback():
    print(f"\n{SEP}\nTEST 1: DB initialization, schema migrations & transaction rollback\n{SEP}")
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as td:
        db_path = Path(td) / "test_knowledge.db"
        db = KnowledgeDatabase(db_path)

        # Verify tables created
        tables = db.execute("SELECT name FROM sqlite_master WHERE type='table'")
        table_names = {t["name"] for t in tables}
        assert "model_runs" in table_names
        assert "creative_decisions" in table_names
        assert "learning_events" in table_names
        assert "knowledge_patterns" in table_names
        assert "experiments" in table_names

        # Verify rollback on exception
        try:
            with db.transaction() as cur:
                cur.execute("INSERT INTO model_runs (id, model_provider, model_name, model_version, prompt_version, task_type, created_at) VALUES ('r_bad', 'google', 'gemini', 'v1', 'v1', 'task', '2026-09-01T00:00:00Z')")
                raise RuntimeError("Simulated crash mid-transaction")
        except RuntimeError:
            pass

        row = db.execute_single("SELECT * FROM model_runs WHERE id = 'r_bad'")
        assert row is None, "Rollback failed; uncommitted record found!"

        db.close()
        print("  PASS: Database schema migrations initialized; ACID rollback verified.")


def test_02_model_run_tracking():
    print(f"\n{SEP}\nTEST 2: ModelRun registry & execution tracking\n{SEP}")
    repo = KnowledgeRepository(KnowledgeDatabase())
    run = repo.record_model_run(
        model_provider="google",
        model_name="gemini-1.5-pro",
        model_version="002",
        prompt_version="v3.1",
        task_type="hook_selection",
        input_reference="hash_prompt_input_123",
        output_reference="hash_output_json_456",
        latency_ms=420,
        token_usage={"prompt_tokens": 1200, "completion_tokens": 350},
        success=True,
    )
    assert run.id.startswith("run_")
    assert run.model_name == "gemini-1.5-pro"
    print(f"  Recorded ModelRun: {run.id}, provider={run.model_provider}, latency={run.latency_ms}ms")
    print("  PASS: Model run successfully tracked.")


def test_03_creative_decision_structured():
    print(f"\n{SEP}\nTEST 3: CreativeDecision structured records (zero CoT leakage)\n{SEP}")
    repo = KnowledgeRepository(KnowledgeDatabase())
    repo.record_model_run("google", "gemini-1.5-pro", run_id="run_test_01")
    dec = repo.record_creative_decision(
        project_id="show_future_tech",
        episode_id="ep_42",
        clip_id="clip_007",
        decision_type="hook_selection",
        decision_payload={"hook_type": "curiosity_gap", "score": 0.89, "start_time": 12.4},
        reasoning_summary="Selected because the question 'what happens when AI designs its own chips' creates immediate suspense.",
        model_run_id="run_test_01",
        memory_context_ids=["pat_01", "pat_02"],
    )
    assert dec.id.startswith("dec_")
    assert dec.decision_payload["hook_type"] == "curiosity_gap"
    assert "chain_of_thought" not in dec.to_dict()

    decisions = repo.get_decisions_for_clip("show_future_tech", "clip_007")
    assert len(decisions) == 1
    assert decisions[0].reasoning_summary == dec.reasoning_summary
    print(f"  Recorded Decision: {dec.id}, type={dec.decision_type}")
    print("  PASS: Structured decision recorded cleanly without private CoT.")


def test_04_learning_event_idempotency():
    print(f"\n{SEP}\nTEST 4: LearningEvent ingestion & idempotency (duplicate events skipped)\n{SEP}")
    repo = KnowledgeRepository(KnowledgeDatabase())

    evt1, inserted1 = repo.record_learning_event(
        event_type=LearningEventType.HOOK_PERFORMED_WELL.value,
        source_type="PRODUCTION",
        source_id="clip_viral_101",
        project_id="proj_alpha",
        account_id="acc_main",
        payload={"views": 50000, "retention_5s": 88.5},
    )
    assert inserted1 is True

    # Duplicate ingestion with same identity
    evt2, inserted2 = repo.record_learning_event(
        event_type=LearningEventType.HOOK_PERFORMED_WELL.value,
        source_type="PRODUCTION",
        source_id="clip_viral_101",
        project_id="proj_alpha",
        account_id="acc_main",
        payload={"views": 50000, "retention_5s": 88.5},
    )
    assert inserted2 is False
    assert evt1.id == evt2.id

    print(f"  Event 1 inserted: {inserted1}, Event 2 duplicate skipped: {not inserted2}")
    print("  PASS: Learning event idempotency verified.")


def test_05_knowledge_pattern_lifecycle():
    print(f"\n{SEP}\nTEST 5: KnowledgePattern lifecycle (CANDIDATE -> VALIDATED -> ACTIVE -> REJECTED)\n{SEP}")
    repo = KnowledgeRepository(KnowledgeDatabase())

    # Step 1: Record decision so event induction links it
    repo.record_creative_decision(
        project_id="proj_beta", episode_id="ep_01", clip_id="clip_b01",
        decision_type="hook_selection", decision_payload={"hook_type": "shock_statement"},
        reasoning_summary="Bold opening statement.",
    )

    # 1 success -> CANDIDATE
    repo.record_learning_event(
        event_type=LearningEventType.HOOK_PERFORMED_WELL.value,
        source_type="PRODUCTION", source_id="clip_b01", project_id="proj_beta",
    )
    p1 = repo.get_pattern("pat_hook_shock_statement_proj_beta")
    assert p1 is not None
    assert p1.status == PatternStatus.CANDIDATE.value
    assert p1.success_count == 1

    # 3 successes -> VALIDATED
    for i in range(2, 4):
        cid = f"clip_b{i:02d}"
        repo.record_creative_decision("proj_beta", "ep_01", cid, "hook_selection", {"hook_type": "shock_statement"}, "Reason")
        repo.record_learning_event(LearningEventType.HOOK_PERFORMED_WELL.value, "PRODUCTION", cid, "proj_beta")

    p2 = repo.get_pattern("pat_hook_shock_statement_proj_beta")
    assert p2.status == PatternStatus.VALIDATED.value
    assert p2.success_count == 3

    # 5 successes -> ACTIVE
    for i in range(4, 7):
        cid = f"clip_b{i:02d}"
        repo.record_creative_decision("proj_beta", "ep_01", cid, "hook_selection", {"hook_type": "shock_statement"}, "Reason")
        repo.record_learning_event(LearningEventType.HOOK_PERFORMED_WELL.value, "PRODUCTION", cid, "proj_beta")

    p3 = repo.get_pattern("pat_hook_shock_statement_proj_beta")
    assert p3.status == PatternStatus.ACTIVE.value
    assert p3.confidence >= 0.50

    # Series of failures -> REJECTED
    for i in range(7, 15):
        cid = f"clip_b{i:02d}"
        repo.record_creative_decision("proj_beta", "ep_01", cid, "hook_selection", {"hook_type": "shock_statement"}, "Reason")
        repo.record_learning_event(LearningEventType.HOOK_PERFORMED_POORLY.value, "PRODUCTION", cid, "proj_beta")

    p4 = repo.get_pattern("pat_hook_shock_statement_proj_beta")
    assert p4.status == PatternStatus.REJECTED.value
    assert p4.failure_count > p4.success_count

    print(f"  Pattern progressed: CANDIDATE -> VALIDATED -> ACTIVE -> REJECTED (conf: {p4.confidence})")
    print("  PASS: Knowledge pattern lifecycle state machine verified.")


def test_06_mathematical_confidence_calculation():
    print(f"\n{SEP}\nTEST 6: Mathematical Bayesian confidence calculation\n{SEP}")
    # 1 success out of 1 trial should NOT be 1.0 (Laplace + sample dampener prevents 1-hit wonder false activation)
    c_1_of_1 = _calculate_confidence(1, 0)
    assert c_1_of_1 < 0.35, f"1/1 sample should be damped, got {c_1_of_1}"

    # 5 successes out of 5 trials
    c_5_of_5 = _calculate_confidence(5, 0)
    assert 0.45 < c_5_of_5 < 0.80

    # 20 successes out of 22 trials
    c_20_of_22 = _calculate_confidence(20, 2)
    assert c_20_of_22 > 0.65

    # 10 successes out of 20 trials (50% win rate)
    c_10_of_20 = _calculate_confidence(10, 10)
    assert c_10_of_20 < 0.45

    print(f"  Confidence 1/1: {c_1_of_1}, 5/5: {c_5_of_5}, 20/22: {c_20_of_22}, 10/20: {c_10_of_20}")
    print("  PASS: Mathematical confidence calculation avoids false high confidence on small samples.")


# ─── Tests 7 through 11: Analytics, Experiments & LLM Independence ────────────

def test_07_analytics_feedback_loop():
    print(f"\n{SEP}\nTEST 7: Analytics snapshot to LearningEvent feedback loop\n{SEP}")
    repo = KnowledgeRepository(KnowledgeDatabase())

    snapshot = AnalyticsSnapshot(
        snapshot_id="snap_101",
        job_id="job_p17",
        clip_id="clip_p17_viral",
        external_id="yt_vid_999",
        metrics=PerformanceMetrics(
            external_id="yt_vid_999",
            platform="youtube_shorts",
            provider="YouTubePublisher",
            account_id="acc_main",
            views=85000,
            average_percentage_viewed=82.5,
            retention_curve=[{"time_sec": 5.0, "retention_pct": 86.0}],
            is_synthetic=True,
        ),
    )

    events = repo.ingest_analytics_outcome(snapshot, project_id="show_science")
    assert len(events) >= 1
    assert events[0].event_type == LearningEventType.HOOK_PERFORMED_WELL.value
    assert events[0].payload["views"] == 85000
    assert events[0].source_type == "SYNTHETIC"

    print(f"  Ingested analytics -> Generated event: {events[0].event_type}")
    print("  PASS: Analytics performance seamlessly ingested into learning events.")


def test_08_experiment_framework():
    print(f"\n{SEP}\nTEST 8: Experiment framework (hypothesis, variant A/B, winner determination)\n{SEP}")
    repo = KnowledgeRepository(KnowledgeDatabase())

    exp = repo.create_experiment(
        hypothesis="Dynamic animated subtitles achieve higher completion rate than static subtitles.",
        variant_a={"subtitle_style": "word_by_word_karaoke"},
        variant_b={"subtitle_style": "static_bottom_line"},
        target_metrics=["average_percentage_viewed"],
    )
    assert exp.status == ExperimentStatus.RUNNING.value

    # Record 5 samples for Variant A (High retention ~ 85%)
    for _ in range(5):
        repo.record_experiment_sample(exp.id, "A", {"average_percentage_viewed": 85.0})

    # Record 5 samples for Variant B (Low retention ~ 60%)
    exp_updated = None
    for _ in range(5):
        exp_updated = repo.record_experiment_sample(exp.id, "B", {"average_percentage_viewed": 60.0})

    assert exp_updated is not None
    assert exp_updated.status == ExperimentStatus.SUPPORTED.value
    assert exp_updated.winner == "VARIANT_A"
    assert exp_updated.confidence >= 0.60
    assert exp_updated.results_a["average_percentage_viewed"] == 85.0
    assert exp_updated.results_b["average_percentage_viewed"] == 60.0

    print(f"  Experiment Winner: {exp_updated.winner}, Status: {exp_updated.status}, Confidence: {exp_updated.confidence}")
    print("  PASS: Experiment framework evaluated variant comparison cleanly.")


def test_09_structured_knowledge_retrieval():
    print(f"\n{SEP}\nTEST 9: Structured knowledge retrieval for AI planning context\n{SEP}")
    repo = KnowledgeRepository(KnowledgeDatabase())

    # Create active pattern
    repo.create_pattern(
        pattern_type="hook_retention",
        statement="Questions creating an unresolved curiosity gap achieve >80% 5s retention in Science podcasts.",
        conditions={"genre": "science", "format": "ambient_blur"},
        evidence_count=18,
        success_count=15,
        failure_count=3,
        confidence=0.82,
        status=PatternStatus.ACTIVE.value,
        scope=KnowledgeScope.GLOBAL.value,
    )

    ctx_list = repo.query_knowledge(pattern_type="hook_retention", min_confidence=0.70)
    assert len(ctx_list) >= 1
    ctx = ctx_list[0]
    prompt_str = ctx.to_prompt_context()

    assert "HOOK_RETENTION" in prompt_str
    assert "0.82" in prompt_str
    assert "15/18" in prompt_str

    print(f"  Generated Prompt Context:\n{prompt_str}")
    print("  PASS: Structured context formatted for model-independent prompt consumption.")


def test_10_llm_replacement_test():
    print(f"\n{SEP}\nTEST 10: LLM Replacement Test (LLM_B seamlessly consumes knowledge from LLM_A)\n{SEP}")
    repo = KnowledgeRepository(KnowledgeDatabase())

    # 1. LLM_A (e.g. Gemini-1.5-Pro) produces a decision & learning evidence
    run_a = repo.record_model_run("google", "gemini-1.5-pro", "001", "v1", "hook_selection", run_id="run_a_01")
    for i in range(1, 7):
        cid = f"clip_shared_{i:02d}"
        repo.record_creative_decision(
            project_id="proj_shared", episode_id="ep_01", clip_id=cid,
            decision_type="hook_selection", decision_payload={"hook_type": "mystery_reveal"},
            reasoning_summary="Presents a puzzle in sentence 1.",
            model_run_id=run_a.id,
        )
        repo.record_learning_event(LearningEventType.HOOK_PERFORMED_WELL.value, "PRODUCTION", cid, "proj_shared")

    # Verify pattern is formed under LLM_A
    pat_under_a = repo.get_pattern("pat_hook_mystery_reveal_proj_shared")
    assert pat_under_a is not None
    assert pat_under_a.status in (PatternStatus.VALIDATED.value, PatternStatus.ACTIVE.value)

    # 2. LLM_A is DISCARDED / REPLACED by LLM_B (e.g. Claude-3.5-Sonnet)
    # LLM_B starts fresh without any shared memory, querying only the canonical KnowledgeRepository
    run_b = repo.record_model_run("anthropic", "claude-3-5-sonnet", "20241022", "v2.0", "editorial_planning", run_id="run_b_01")

    # LLM_B queries repository for project knowledge
    retrieved_for_b = repo.query_knowledge(project_id="proj_shared", min_confidence=0.35)
    assert len(retrieved_for_b) >= 1
    assert any("mystery_reveal" in r.statement for r in retrieved_for_b)

    # LLM_B successfully makes an informed decision utilizing LLM_A's accumulated learning
    dec_b = repo.record_creative_decision(
        project_id="proj_shared", episode_id="ep_02", clip_id="clip_shared_02",
        decision_type="editorial_plan",
        decision_payload={"chosen_hook": "mystery_reveal", "pacing": "fast"},
        reasoning_summary="Applied historical mystery_reveal hook pattern validated in previous episode.",
        model_run_id=run_b.id,
        memory_context_ids=[retrieved_for_b[0].pattern_id],
    )

    assert dec_b.model_run_id == run_b.id
    assert retrieved_for_b[0].pattern_id in dec_b.memory_context_ids

    print(f"  LLM_A ({run_a.model_name}) generated pattern -> LLM_B ({run_b.model_name}) retrieved and applied it.")
    print("  PASS: Zero knowledge lost upon LLM swap. Total model independence proven.")


def test_11_tenant_project_isolation():
    print(f"\n{SEP}\nTEST 11: Tenant & project scope isolation (GLOBAL vs ACCOUNT vs PROJECT)\n{SEP}")
    repo = KnowledgeRepository(KnowledgeDatabase())

    # Global pattern
    repo.create_pattern(
        pattern_type="pacing", statement="Fast opening pacing works universally.",
        conditions={}, confidence=0.90, status=PatternStatus.ACTIVE.value,
        scope=KnowledgeScope.GLOBAL.value, pattern_id="pat_global_1",
    )
    # Account A private pattern
    repo.create_pattern(
        pattern_type="hook_style", statement="Account A specific dark humor hooks.",
        conditions={}, confidence=0.88, status=PatternStatus.ACTIVE.value,
        scope=KnowledgeScope.ACCOUNT.value, account_id="acc_alpha", pattern_id="pat_acc_a",
    )
    # Account B private pattern
    repo.create_pattern(
        pattern_type="hook_style", statement="Account B specific educational hooks.",
        conditions={}, confidence=0.88, status=PatternStatus.ACTIVE.value,
        scope=KnowledgeScope.ACCOUNT.value, account_id="acc_beta", pattern_id="pat_acc_b",
    )

    # Query from Account A
    res_a = repo.query_knowledge(account_id="acc_alpha", min_confidence=0.50)
    a_ids = {r.pattern_id for r in res_a}
    assert "pat_global_1" in a_ids
    assert "pat_acc_a" in a_ids
    assert "pat_acc_b" not in a_ids, "Cross-tenant leak: Account A saw Account B pattern!"

    # Query from Account B
    res_b = repo.query_knowledge(account_id="acc_beta", min_confidence=0.50)
    b_ids = {r.pattern_id for r in res_b}
    assert "pat_global_1" in b_ids
    assert "pat_acc_b" in b_ids
    assert "pat_acc_a" not in b_ids, "Cross-tenant leak: Account B saw Account A pattern!"

    print("  PASS: Tenant isolation verified. Private patterns strictly segregated.")


# ─── Tests 12 through 16: Security, Export/Import, Concurrency & Migration ───

def test_12_secret_leakage_audit():
    print(f"\n{SEP}\nTEST 12: Security & Zero Secret Leakage Audit\n{SEP}")
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as td:
        db_path = Path(td) / "sec_test.db"
        repo = KnowledgeRepository(KnowledgeDatabase(db_path))

        secret_token = "ya29.SECRET_TOKEN_DO_NOT_LEAK_9999"

        # Record decision and event with standard payload
        repo.record_creative_decision(
            project_id="proj_sec", episode_id="ep_01", clip_id="clip_01",
            decision_type="hook_choice", decision_payload={"hook": "curiosity"},
            reasoning_summary="Legitimate reasoning summary.",
        )
        repo.record_learning_event(
            event_type=LearningEventType.HOOK_PERFORMED_WELL.value,
            source_type="PRODUCTION", source_id="clip_01",
            payload={"views": 10000},
        )

        # Inspect raw SQL dump
        db = repo.db
        rows_dec = db.execute("SELECT * FROM creative_decisions")
        rows_evt = db.execute("SELECT * FROM learning_events")

        raw_dump = json.dumps([dict(r) for r in rows_dec] + [dict(r) for r in rows_evt])
        assert secret_token not in raw_dump
        assert "client_secret" not in raw_dump
        assert "refresh_token" not in raw_dump

        db.close()
        print("  PASS: Zero credentials detected in persistent knowledge tables.")


def test_13_portable_export_and_import():
    print(f"\n{SEP}\nTEST 13: Portable export & import snapshot integrity\n{SEP}")
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as td:
        export_file = Path(td) / "knowledge_export.json"
        db1_path = Path(td) / "db1.db"
        db2_path = Path(td) / "db2.db"

        repo1 = KnowledgeRepository(KnowledgeDatabase(db1_path))
        repo1.record_model_run("google", "gemini", "v1", "v1", "task1")
        repo1.record_creative_decision("p1", "e1", "c1", "hook", {"hook": "bold"}, "Reason")
        repo1.create_pattern("pacing", "Fast cuts", {}, 10, 8, 2, 0.75, status=PatternStatus.ACTIVE.value)

        # Export JSON & JSONL
        repo1.export_knowledge(export_file)
        assert export_file.exists()
        assert export_file.stat().st_size > 100

        jsonl_file = Path(td) / "learning_dataset.jsonl"
        repo1.export_learning_dataset_jsonl(jsonl_file)
        assert jsonl_file.exists()
        assert jsonl_file.stat().st_size > 50

        # Import into fresh DB
        repo2 = KnowledgeRepository(KnowledgeDatabase(db2_path))
        imported_count = repo2.import_knowledge(export_file)
        assert imported_count >= 3

        patterns = repo2.query_knowledge(min_confidence=0.50)
        assert len(patterns) >= 1
        assert patterns[0].statement == "Fast cuts"

        repo1.db.close()
        repo2.db.close()
        print(f"  Exported JSON + JSONL -> Imported {imported_count} records into fresh DB.")
        print("  PASS: Portable snapshot export and import verified.")


def test_14_concurrent_thread_safety():
    print(f"\n{SEP}\nTEST 14: Concurrent thread safety & ACID transaction isolation\n{SEP}")
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as td:
        db_path = Path(td) / "concur.db"
        repo = KnowledgeRepository(KnowledgeDatabase(db_path))
        errors = []

        def _worker(thread_idx: int):
            try:
                for i in range(10):
                    cid = f"clip_th_{thread_idx}_{i}"
                    repo.record_creative_decision("proj_concur", "ep_01", cid, "hook", {"idx": i}, "Summary")
                    repo.record_learning_event(LearningEventType.HOOK_PERFORMED_WELL.value, "PRODUCTION", cid, "proj_concur")
            except Exception as e:
                errors.append(e)

        threads = [threading.Thread(target=_worker, args=(t,)) for t in range(5)]
        for t in threads: t.start()
        for t in threads: t.join(timeout=15)

        assert len(errors) == 0, f"Concurrent execution produced errors: {errors}"
        decisions = repo.db.execute("SELECT COUNT(*) as cnt FROM creative_decisions WHERE project_id = 'proj_concur'")
        assert decisions[0]["cnt"] == 50

        repo.db.close()
        print(f"  5 threads concurrently wrote 50 decisions and events with 0 errors.")
        print("  PASS: ACID transaction isolation under concurrent multi-threaded load verified.")


def test_15_failure_recovery_resilience():
    print(f"\n{SEP}\nTEST 15: Failure recovery & corrupted store resilience\n{SEP}")
    repo = KnowledgeRepository(KnowledgeDatabase())

    # Invalid import file
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as td:
        corrupt_file = Path(td) / "bad.json"
        corrupt_file.write_text("{ MALFORMED JSON !!!", encoding="utf-8")
        try:
            repo.import_knowledge(corrupt_file)
        except Exception:
            pass  # Handled safely

    # Verify repo still fully operational
    run = repo.record_model_run("google", "gemini", "v1", "v1", "recovery_check")
    assert run.id.startswith("run_")
    print("  PASS: Knowledge base resilience to malformed inputs verified.")


def test_16_creative_memory_migration():
    print(f"\n{SEP}\nTEST 16: Historical Phase 10 Creative Memory migration check\n{SEP}")
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as td:
        mem_dir = Path(td) / "legacy_memory"
        mem_dir.mkdir()

        # Write mock legacy Phase 10 files
        ev_file = mem_dir / "evidence_001.json"
        ev_file.write_text(json.dumps({
            "evidence_id": "ev_leg_123",
            "clip_id": "clip_leg_01",
            "episode_id": "ep_leg_01",
            "observation": "High retention with curiosity opening",
            "outcome": "POSITIVE",
            "source_type": "PRODUCTION",
            "magnitude": 0.85,
        }), encoding="utf-8")

        mem_file = mem_dir / "memory_001.json"
        mem_file.write_text(json.dumps({
            "memory_id": "mem_leg_456",
            "memory_type": "hook_retention",
            "statement": "Curiosity hooks perform well in legacy podcasts.",
            "sample_size": 12,
            "success_count": 10,
            "failure_count": 2,
            "confidence": 0.81,
            "status": "ACTIVE",
            "scope": "GLOBAL",
        }), encoding="utf-8")

        repo = KnowledgeRepository(KnowledgeDatabase())
        result = repo.migrate_from_creative_memory(mem_dir)

        assert result["evidence"] == 1
        assert result["memories"] == 1

        patterns = repo.query_knowledge(min_confidence=0.70)
        assert len(patterns) >= 1
        assert "legacy podcasts" in patterns[0].statement

        print(f"  Migrated {result['evidence']} evidence records and {result['memories']} memories into SQL.")
        print("  PASS: Legacy Creative Memory migration verified.")


# ─── Regression Tests 17 through 21 (Phases 11–16) ────────────────────────────

def test_17_phase15_16_regression():
    print(f"\n{SEP}\nTEST 17: Phase 15/16 Production Readiness Regression (14/14 tests)\n{SEP}")
    res = subprocess.run(
        [sys.executable, "-u", "brain/test_production_readiness.py"],
        capture_output=True, text=True, cwd=str(Path(__file__).parent.parent)
    )
    if res.returncode != 0:
        print(res.stdout)
        print(res.stderr)
        assert False, f"Phase 15/16 regression failed with exit code {res.returncode}"
    print("  PASS: Phase 15/16 test suite passed with 0 regressions.")


def test_18_phase14_regression():
    print(f"\n{SEP}\nTEST 18: Phase 14 Queue Regression (41/41 tests)\n{SEP}")
    res = subprocess.run(
        [sys.executable, "-u", "brain/test_phase14_queue.py"],
        capture_output=True, text=True, cwd=str(Path(__file__).parent.parent)
    )
    if res.returncode != 0:
        print(res.stdout)
        print(res.stderr)
        assert False, f"Phase 14 regression failed with exit code {res.returncode}"
    print("  PASS: Phase 14 test suite passed with 0 regressions.")


def test_19_phase13_regression():
    print(f"\n{SEP}\nTEST 19: Phase 13 Real Provider Regression (30/30 tests)\n{SEP}")
    res = subprocess.run(
        [sys.executable, "-u", "brain/test_real_provider.py"],
        capture_output=True, text=True, cwd=str(Path(__file__).parent.parent)
    )
    if res.returncode != 0:
        print(res.stdout)
        print(res.stderr)
        assert False, f"Phase 13 regression failed with exit code {res.returncode}"
    print("  PASS: Phase 13 test suite passed with 0 regressions.")


def test_20_phase12_regression():
    print(f"\n{SEP}\nTEST 20: Phase 12 Delivery Layer Regression (27/27 tests)\n{SEP}")
    res = subprocess.run(
        [sys.executable, "-u", "brain/test_publishing.py"],
        capture_output=True, text=True, cwd=str(Path(__file__).parent.parent)
    )
    if res.returncode != 0:
        print(res.stdout)
        print(res.stderr)
        assert False, f"Phase 12 regression failed with exit code {res.returncode}"
    print("  PASS: Phase 12 test suite passed with 0 regressions.")


def test_21_phase11_regression():
    print(f"\n{SEP}\nTEST 21: Phase 11 Orchestrator Regression (23/23 tests)\n{SEP}")
    res = subprocess.run(
        [sys.executable, "-u", "brain/test_orchestrator.py"],
        capture_output=True, text=True, cwd=str(Path(__file__).parent.parent)
    )
    if res.returncode != 0:
        print(res.stdout)
        print(res.stderr)
        assert False, f"Phase 11 regression failed with exit code {res.returncode}"
    print("  PASS: Phase 11 test suite passed with 0 regressions.")


# ─── Master Runner ────────────────────────────────────────────────────────────

if __name__ == "__main__":
    tests = [
        ("TEST 1  — DB Init & Rollback",     test_01_db_init_and_rollback),
        ("TEST 2  — ModelRun Registry",      test_02_model_run_tracking),
        ("TEST 3  — Creative Decisions",     test_03_creative_decision_structured),
        ("TEST 4  — Event Idempotency",      test_04_learning_event_idempotency),
        ("TEST 5  — Pattern Lifecycle",      test_05_knowledge_pattern_lifecycle),
        ("TEST 6  — Bayesian Confidence",    test_06_mathematical_confidence_calculation),
        ("TEST 7  — Analytics Feedback",     test_07_analytics_feedback_loop),
        ("TEST 8  — Experiment Framework",   test_08_experiment_framework),
        ("TEST 9  — Knowledge Retrieval",    test_09_structured_knowledge_retrieval),
        ("TEST 10 — LLM Replacement",        test_10_llm_replacement_test),
        ("TEST 11 — Tenant Isolation",       test_11_tenant_project_isolation),
        ("TEST 12 — Secret Leakage Audit",   test_12_secret_leakage_audit),
        ("TEST 13 — Export / Import",        test_13_portable_export_and_import),
        ("TEST 14 — Concurrency & ACID",     test_14_concurrent_thread_safety),
        ("TEST 15 — Failure Recovery",       test_15_failure_recovery_resilience),
        ("TEST 16 — Legacy Memory Migration", test_16_creative_memory_migration),
        ("TEST 17 — Phase 15/16 Regression", test_17_phase15_16_regression),
        ("TEST 18 — Phase 14 Regression",    test_18_phase14_regression),
        ("TEST 19 — Phase 13 Regression",    test_19_phase13_regression),
        ("TEST 20 — Phase 12 Regression",    test_20_phase12_regression),
        ("TEST 21 — Phase 11 Regression",    test_21_phase11_regression),
    ]

    passed, failed = [], []
    for label, fn in tests:
        try:
            fn()
            passed.append(label)
        except AssertionError as e:
            failed.append((label, str(e)))
            print(f"  FAIL [{label}]: {e}")
        except Exception as e:
            import traceback
            failed.append((label, f"EXCEPTION: {e}"))
            print(f"  ERROR [{label}]: {e}")
            traceback.print_exc()

    print(f"\n{SEP}")
    print("PHASE 17 PERSISTENT KNOWLEDGE BASE & LEARNING TEST RESULTS")
    print(SEP)
    print(f"  PASSED: {len(passed)}/{len(tests)}")
    if failed:
        print(f"  FAILED: {len(failed)}/{len(tests)}")
        for label, reason in failed:
            print(f"    [{label}] {reason}")
    else:
        print("  ALL 21 TESTS PASSED (100%). Exit code: 0")
    print(SEP)

    sys.exit(0 if not failed else 1)
